# Generated by Django 4.1.7 on 2023-04-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_linkshortenermodel_owner_viewlinksmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewlinksmodel",
            name="owner",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner1",
                to="accounts.linkshortenermodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="viewlinksmodel",
            name="see_url",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
