# Generated by Django 4.1.7 on 2023-04-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_viewlinksmodel_owner_alter_viewlinksmodel_see_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkshortenermodel",
            name="url_viewed",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
