# Generated by Django 4.1.7 on 2023-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_linkshortenermodel_url_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkshortenermodel",
            name="see_url",
            field=models.BooleanField(default=False),
        ),
    ]
